### ISSUE TITLE
Can not record with wiremock

### ISSUE THREAD

**Issue by user3748173** [rodolpheche/wiremock-docker#10]
I am asking it hire because I have no idea where else should I ask it.

I have created next docker-compose.yml file:
`version: '3.1'
services:
  wordpress_test:
    container_name: wp_test
    restart: always
    image: wordpress
    depends_on:
      - db_test
    links:
       - wiremock_wp:wiremock
    ports:
      - 8989:80
    environment:
      WORDPRESS_DB_HOST: db_test:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    tty: true
  db_test:
    container_name: wp_test_db
    restart: always
    image: mysql:5.7
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wiremock_wp:
    container_name: wp_wiremock
    image: rodolpheche/wiremock
    ports:
      - 8283:8080
      - 8484:8443`

Then i added the hello.json files to the wiremock directory and after restart all is working accessing `http://localhost:8283/hello` I get "the __files/hello.json" output. But when I am trying to record the `http://localhost:8283/hello`  request with `http://localhost:8283/__admin/recorder/` I get next error:

`Problem accessing /hello. Reason:
    Server Error
Caused by:
java.lang.RuntimeException: wiremock.org.apache.http.conn.HttpHostConnectException: Connect to localhost:8283 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
	at com.github.tomakehurst.wiremock.http.ProxyResponseRenderer.render(ProxyResponseRenderer.java:87)
	at com.github.tomakehurst.wiremock.http.StubResponseRenderer.buildResponse(StubResponseRenderer.java:57)
	at com.github.tomakehurst.wiremock.http.StubResponseRenderer.render(StubResponseRenderer.java:51)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:47)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:108)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.servlets.gzip.GzipHandler.handle(GzipHandler.java:479)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:499)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: wiremock.org.apache.http.conn.HttpHostConnectException: Connect to localhost:8283 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
	at wiremock.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at wiremock.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at wiremock.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at wiremock.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at wiremock.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at wiremock.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at wiremock.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at wiremock.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at wiremock.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.github.tomakehurst.wiremock.http.ProxyResponseRenderer.render(ProxyResponseRenderer.java:71)
	... 21 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at wiremock.org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at wiremock.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 30 more
Caused by:
wiremock.org.apache.http.conn.HttpHostConnectException: Connect to localhost:8283 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
	at wiremock.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at wiremock.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at wiremock.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at wiremock.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at wiremock.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at wiremock.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at wiremock.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at wiremock.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at wiremock.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.github.tomakehurst.wiremock.http.ProxyResponseRenderer.render(ProxyResponseRenderer.java:71)
	at com.github.tomakehurst.wiremock.http.StubResponseRenderer.buildResponse(StubResponseRenderer.java:57)
	at com.github.tomakehurst.wiremock.http.StubResponseRenderer.render(StubResponseRenderer.java:51)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:47)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:108)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.servlets.gzip.GzipHandler.handle(GzipHandler.java:479)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:499)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at wiremock.org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at wiremock.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 30 more
Caused by:
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at wiremock.org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at wiremock.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at wiremock.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at wiremock.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at wiremock.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at wiremock.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at wiremock.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at wiremock.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at wiremock.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at wiremock.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.github.tomakehurst.wiremock.http.ProxyResponseRenderer.render(ProxyResponseRenderer.java:71)
	at com.github.tomakehurst.wiremock.http.StubResponseRenderer.buildResponse(StubResponseRenderer.java:57)
	at com.github.tomakehurst.wiremock.http.StubResponseRenderer.render(StubResponseRenderer.java:51)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:47)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:108)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.servlets.gzip.GzipHandler.handle(GzipHandler.java:479)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:499)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)`

**What is different when I accesing the `http://localhost:8283/hello` url if I am not recording and when I am recording? What might cause the error? How can I debug or get more information about the error cause?**

**Comment by rodolpheche** [comment]
The target url you filled in recorder is wrong. Wiremock recorder is a proxy, the HTTP request is made into the container, so you must target a known and accessible url by the container. In your example, you should have fill http://localhost:8080 but it doesn't work too : it seems you couldn't both serve stub and record these stubs with the same instance. For more details, ask it to @tomakehurst 

However, you can explode this instance. Here is a docker-compose example file :
```
version: '3.1'

services:

  wiremock_hello:
    image: rodolpheche/wiremock
    volumes:
      - ./hello/stubs:/home/wiremock

  wiremock_recorder:
    image: rodolpheche/wiremock
    ports:
      - 8380:8080
    links:
      - wiremock_hello:wiremock-hello
    volumes:
      - ./record:/home/wiremock
```
* Go to http://localhost:8380/__admin/recorder and fill the field with **http://wiremock-hello:8080**, then press record
* Now, you can record the hello stubs with this url : http://localhost:8380/hello
